config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    resources :checks
  end

  scope module: :web do
    root 'home#index'

    scope :auth do
      post '/:provider', to: 'sessions#auth', as: :auth_request
      get '/:provider/callback', to: 'sessions#create', as: :callback_auth
      get :logout, to: 'sessions#destroy', as: :logout
    end

    resources :repositories, only: %i[index new create show] do
      resources :checks, only: %i[show create], controller: 'repositories/checks'
    end
    resources :home, only: %i[index]
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/views/shared/_flash_messages.html.slim
.container
  - flash.each do |type, message|
    - @class = bootstrap_alert_class(type)
    .alert-dismissible.fade.show class="alert alert-#{@class}" role='alert'
      = message

app/views/shared/_header.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4'
        = image_tag('logo.png', size: '30x30')
      ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
        li.nav-item.me-2
          = link_to t('header.main'), root_path, class: 'nav-link text-dark'
        - if user_present?
          li.nav-item.me-2
            = link_to t('header.repositories'),
              repositories_path, class: 'nav-link text-dark'
    ul.nav.nav-pills
      - if user_present?
        li.nav-item.me-2
          div class='nav-link text-secondary' = current_user_email
      li.nav-item.me-2
        - if user_present?
          = link_to t('header.logout'), logout_path, class: 'nav-link text-dark'
        - else
          = button_to t('header.login'), auth_request_path(:github),
            class: 'nav-link text-dark'