config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    resources :checks
  end

  scope module: :web do
    root 'home#index'

    scope :auth do
      post '/:provider', to: 'sessions#auth', as: :auth_request
      get '/:provider/callback', to: 'sessions#create', as: :callback_auth
      get :logout, to: 'sessions#destroy', as: :logout
    end

    resources :repositories, only: %i[index new create show] do
      resources :checks, only: %i[show create], controller: 'repositories/checks'
    end
    resources :home, only: %i[index]
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  extend Enumerize
  belongs_to :user
  has_many :checks, dependent: :destroy

  validates :github_id, presence: true, uniqueness: true

  enumerize :language, in: %i[ruby javascript]
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  include AASM
  belongs_to :repository

  if ActiveRecord::Base.connection.adapter_name == 'PostgreSQL'
    attribute :result, :json, default: -> { {} }
  else
    serialize :result, coder: JSON
  end

  aasm do # aasm_state field
    state :created, initial: true
    state :finished, :failed

    event :end_processing do
      transitions to: :finished
    end

    event :fail do
      transitions to: :failed
    end
  end

  def short_id
    commit_id&.slice(..6)
  end

  def passed?
    result&.values&.reduce(true) { |a, v| a && v['success'] } || false
  end
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ChecksController < Web::ApplicationController
      include Pundit::Authorization

      before_action -> { authorize Repository::Check }

      before_action :set_repository, only: :create
      before_action :set_check, only: :show

      attr_reader :check

      def show
        redirect_to :repositories unless @check
      end

      def create
        @check = @repository.checks.create!
        CheckRepositoryJob.perform_later(@check.id)
        redirect_to repository_path(@repository)
      end

      private

      def set_repository
        @repository = Repository.find(params.require(:repository_id).to_i)
      end

      def set_check
        @check = Repository::Check.find_by(id: params.require(:id).to_i)
      end
    end
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

require_relative '../../../lib/github/client'

module Web
  class RepositoriesController < Web::ApplicationController
    include Pundit::Authorization

    before_action -> { authorize Repository }
    before_action :set_github_id, only: :create
    before_action :set_repository, only: :show

    def index
      @repositories = Repository.where(user: current_user)
    end

    def show
      redirect_to :repositories unless @repository
    end

    def new
      @repository = Repository.new
    end

    def create
      if @github_id.blank? || @github_id.zero?
        redirect_to :new_repository
        return
      end

      git_client = Github::Client.new(current_user)
      repo = git_client.repo_by_id(@github_id)
      Repository.create!(
        user: current_user,
        name: repo[:name],
        full_name: repo[:full_name] || 'Not set',
        language: git_client.primary_language(@github_id),
        github_id: @github_id,
        web_path: repo[:html_url],
        clone_path: repo[:clone_url]
      )
      git_client.register_hook(@github_id, ENV.fetch('BASE_URL', ''))
      redirect_to repositories_path
    end

    private

    def set_github_id
      @github_id = params.require(:repository).permit(:github_id)[:github_id].to_i
    end

    def set_repository
      @repository = Repository.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @repository = nil
    end
  end
end

app/helpers/repository_helper.rb
# frozen_string_literal: true

module RepositoryHelper
  def last_check_status(repository)
    repository.checks.order(created_at: :desc).first&.passed&.to_s || 'false'
  end
end

app/helpers/web/repositories/checks_helper.rb
# frozen_string_literal: true

module Web
  module Repositories
    module ChecksHelper
      def error_count(check)
        check.result&.values&.reduce(0) { |a, v| a + check_error_count(v) }
      end

      def check_error_count(check_item)
        check_item['success'] ? 0 : check_item['result']['summary']['offense_count']
      end

      def error_list(check)
        check.result&.transform_values do |check_result|
          next if check_result['success']

          offenses = filter_positive_offenses(check_result)
          offenses_array = extract_offense_values(offenses)
          offenses_array.sum([])
        end || {}
      end

      def filter_positive_offenses(check_result)
        check_result['result']['files'].filter { |v| v['offense_count'].positive? }
      end

      def extract_offense_values(offenses)
        offenses.map do |offense|
          [{ link: offense['file_name'] || 'unknown' }] + offense['offenses']
        end
      end

      def file_link(check, file_path)
        check.commit_id && "#{check.repository.web_path}/blob/#{check.commit_id}#{file_path}"
      end

      def git_commit_link(check)
        check.short_id && "#{check.repository.web_path}/commit/#{check.short_id}"
      end
    end
  end
end

app/helpers/web/repositories_helper.rb
# frozen_string_literal: true

require_relative '../../../lib/github/client'

module Web
  module RepositoriesHelper
    SUPPORTED_LANGUAGES = %w[Ruby JavaScript].freeze
    def available_projects
      all_repos = Github::Client.new(controller.current_user)
                                .repos
                                .filter { |repo| SUPPORTED_LANGUAGES.include? repo[:language] }
                                .map { |repo| [repo[:name], repo[:id]] }
      assigned_repos = controller.current_user.repository.pluck(:github_id)
      all_repos.filter { |repo| assigned_repos.exclude?(repo[1]) }.sort_by { |a| a[0] }
    end
  end
end

app/views/web/repositories/index.html.slim
= render 'web/shared/fancy_frame' do
  = link_to t('repositories.index.add'),
    new_repository_path, class: 'btn btn-primary'
  table.table.table-striped.table-hover.mt-4
    thead
      tr
        th scope='col' = t('repositories.index.name')
        th scope='col' = t('repositories.index.language')
        th scope='col' = t('repositories.index.last_check_status')
    tbody
      - @repositories.each do |repo|
        tr
          td = link_to repo.name, repository_path(repo)
          td = repo.language
          td = last_check_status(repo)

app/views/web/repositories/new.html.slim
= render 'web/shared/fancy_frame' do
  = simple_form_for @repository do |f|
    = f.input :github_id, collection: available_projects
    = f.submit t('repositories.actions.create'), class: 'btn btn btn-success'

app/views/web/repositories/show.html.slim
= render 'web/shared/fancy_frame' do
  h1 = @repository.full_name
  = button_to t('repositories.actions.check'),
    repository_checks_path(@repository), class: 'btn btn-primary mb-4'

  p
    strong.me-2 = t('repositories.show.name')
    = @repository.full_name
  p
    strong.me-2 = t('repositories.show.language')
    = @repository.language
  p
    strong.me-2 = t('repositories.show.created')
    = human_date(@repository.created_at)
  p
    strong.me-2 = t('repositories.show.updated')
    = human_date(@repository.updated_at)
  hr
  table.table.table-stripped
    thead
      tr
        th = t('checks.index.number')
        th = t('checks.index.status')
        th = t('checks.index.commit_id')
        th = t('checks.index.check_passed')
        th = t('checks.index.created')
    tbody
      - @repository.checks.each do |check|
        tr
          td = link_to check.id, repository_check_path(@repository, check)
          td = human_state(check)
          td = check.short_id && link_to(check.short_id, git_commit_link(check),
            target: '_blank', rel: 'noopener')
          td = check.passed
          td = human_date(check.created_at, :short)